### ISSUE TITLE
Can't set the page number of FormField.

### ISSUE THREAD

**Issue by 1I111I1** [HelloFax/hellosign-java-sdk#11]
https://faq.hellosign.com/hc/en-us/articles/217115577

There is functionality for setting the x and y position, but not for page number.

**Comment by rmelencio** [comment]
Hi @1I111I1 ,

This is in our backlog and we’ll update you when the change are made.

We also encourage our developer community to submit updates to our SDK.

-Ronald

**Comment by cmpaul** [comment]
This has been fixed as of 3.4.0.
