### ISSUE TITLE
Add client_id to signature request

### ISSUE THREAD

**Issue by sjbog** [HelloFax/hellosign-java-sdk#15]
API docs for sending signature request has optional key `client_id` for 

> The client ID of the ApiApp you want to associate with this request.

https://www.hellosign.com/api/reference#SignatureRequest

Please add it, since It's missing in the java sdk v3.4.1

**Comment by cmpaul** [comment]
Thanks @sjbog . 

I'd like to make some more fundamental changes to the SDK to support this sort of thing, but a quick fix might be to update the parameter type accepted by `HelloSignClient.sendSignatureRequest()` from `SignatureRequest` to `AbstractRequest`. This would allow you to submit an `EmbeddedRequest`, which is just a wrapper around `SignatureRequest` and also supplies a `client_id`. 

I created a branch to test this out. Can you take a look and let me know if this would work for you?

https://github.com/HelloFax/hellosign-java-sdk/tree/request_with_clientid

Specifically:
https://github.com/HelloFax/hellosign-java-sdk/commit/1370009c0d53d0e3ef4db8fed1c836c9ecbc6a36

**Comment by sjbog** [comment]
@cmpaul your approach would work, but it's confusing since the API reference differentiates embedded (signing) & signature request.

**Comment by cmpaul** [comment]
@sjbog Agreed, it's not the clearest...

In that case, let's add an additional overloaded function for `HelloSignClient.sendSignatureRequest` to accept both a `SignatureRequest` and a string `client_id`. I can do that in the next day or so.

**Comment by sjbog** [comment]
Why can't `client_id` be added to the `SignatureRequest`? eg to follow the API docs

**Comment by cmpaul** [comment]
@sjbog Yeah, that does make sense and pretty much eliminates the need for `EmbeddedSignatureRequest`, which is along the lines of what I was mentioning earlier about wanting to do some refactoring. I really like the idea of deprecating/simplifying that. 

Let me throw something together...

**Comment by cmpaul** [comment]
@sjbog Take a look at that PR above and let me know if that will work for you.

**Comment by sjbog** [comment]
Thank you @cmpaul, PR seems good

**Comment by cmpaul** [comment]
@sjbog Done!

Please see v3.4.2 for the new capability and let me know if you have any issues. Thanks for your help!
