### ISSUE TITLE
SDK throws an exception when I try call getApiApp with the App ID

### ISSUE THREAD

**Issue by johnnycupcakes** [HelloFax/hellosign-java-sdk#17]
Posting on behalf of Jonathan Weinberg:

Java SDK version 3.4.2 throws com.hellosign.sdk.HelloSignException: org.json.JSONException: JSONObject["oauth"] is not a JSONObject.

This occurs when running the following code and not having oauth enabled for the account: 
Event helloSignEvent = new Event(jsonObject); // jsonObject comes from the event callback 
HelloSignClient client = new HelloSignClient(helloSignApiKey); 
String appId = helloSignEvent.getAppId(); 
ApiApp apiApp = client.getApiApp(appId); // This throws the exception

​When client.getApiApp(appId) is called, it throws this exception​ referenced above because the oauth property is null, and the SDK seems to be expecting this to be an object. If the callback event would send it as an empty object or if it would handle when the value of the property is null, then that should fix the issue.

**Comment by cmpaul** [comment]
@johnnycupcakes Just fixed this with v3.5.1.
