### ISSUE TITLE
get White Labeling feature into the Hellosign java sdk

### ISSUE THREAD

**Issue by armyofda12mnkeys** [HelloFax/hellosign-java-sdk#18]
I heard this feature is in the Curl, Ruby, and Node sdk's but not Java. 
Can you add soon?
Note: this is a big selling point to our business to choose Hellosign (to "de-brand" and control styling).

**Comment by cmpaul** [comment]
Hi @armyofda12mnkeys ,

I've just added this to the latest release, v3.5.1. 

Can you try this out and let me know if this works for you?

Thanks!

**Comment by armyofda12mnkeys** [comment]
I'll try it out tomorrow. I'll let you know, Thanks for quick turnaround!

**Comment by armyofda12mnkeys** [comment]
Hey Chris, 
Quick question. the current way I connect is:

```
           HelloSignClient client = new HelloSignClient(api_key);
           SignatureRequest newRequest = (SignatureRequest)client.createEmbeddedRequest(embedReq);

            List<Signature> signatures = newRequest.getSignatures ();
            Signature patient_signature = signatures.get (0);
            String signature_id = patient_signature.getId ();

            EmbeddedResponse response = client.getEmbeddedSignUrl(signature_id);
            esign_url = response.getSignUrl();
```
To get the White Labeling in my embedded links, do I have to use this ApiApp class? 
if so, would it look something like:
```
           HelloSignClient client = new HelloSignClient(api_key);
//START of new ApiApp code
            ApiApp api_app = new ApiApp();
            api_app.setPrimaryButtonColor ("#FF0000");
            client.createApiApp (api_app);
//END of new ApiApp code
           SignatureRequest newRequest = (SignatureRequest)client.createEmbeddedRequest(embedReq);



            List<Signature> signatures = newRequest.getSignatures ();
            Signature patient_signature = signatures.get (0);
            String signature_id = patient_signature.getId ();

            EmbeddedResponse response = client.getEmbeddedSignUrl(signature_id);
            esign_url = response.getSignUrl();
```

**Comment by armyofda12mnkeys** [comment]
Note: getting an error with above modification where i add ApiApp:
"com.hellosign.sdk.HelloSignException: Must specify name"

**Comment by armyofda12mnkeys** [comment]
Also tried the below (adding a name... then domain since it errored asking for a domain... Im testing on localhost via localhost:9005 so not sure what to put there... said localhost was an invalid domain so changed to the url where I would deploy it if it passes the domain stuff).
Get this error now:             
com.hellosign.sdk.HelloSignException: An app with the same name already exists
Any idea?

```
           HelloSignClient client = new HelloSignClient(api_key);
            ApiApp api_app = new ApiApp();
            api_app.setName ("Client Questionnaire App");
            api_app.setLinkColor ("#FF0000");
            //api_app.setWhiteLabelingOptions (options);
            api_app.setPrimaryButtonColor ("#FF0000");
            api_app.setDomain("wpengine.com");
            client.createApiApp (api_app);
            SignatureRequest newRequest = (SignatureRequest)client.createEmbeddedRequest(embedReq);
```

**Comment by cmpaul** [comment]
Hi @armyofda12mnkeys - looks like you're doing this correctly to *create a new API App*, however sounds like you already have one with that name, so you'll want to *update* your app instead using the `client.updateApiApp(app)` method. 

Once you've updated your API app with these white labeling settings, ALL signature requests created with the app's client ID will display using those settings.

If you want to test just one-off white labeling settings, you can do that by passing one-time white labeling options as a parameter in your JavaScript call, `HelloSign.open()`:

```javascript
HelloSign.open({
    ...
    'whiteLabelingOptions': {
        'link_color': '#FF0000'
    },
    ...
});
```

(This is not very well documented, but you can see how we use this parameter in our front-end JavaScript library here: https://github.com/HelloFax/hellosign-embedded/blob/master/src/embedded.js#L327). 

Try these approaches and let us know if that works!

**Comment by armyofda12mnkeys** [comment]
Hey @cmpaul 
so i tried one-off via whiteLabelingOptions (the JS front-end code) with my old server-side code (no new ApiApp code) and didnt work.
I tried adding updateApiApp too via below to my server-side code (and i used the name of the App I see online at https://www.hellosign.com/home/myAccount?current_tab=api)...
But still get an error:
com.hellosign.sdk.HelloSignException: Cannot update an ApiApp without a client ID. Create one first!

```
            EmbeddedRequest embedReq = new EmbeddedRequest(client_id, request);
            HelloSignClient client = new HelloSignClient(api_key);

            ApiApp api_app = new ApiApp();
            api_app.setName ("ClientQuestionnaireApp");
            api_app.setLinkColor ("#FF0000");
            api_app.setPrimaryButtonColor ("#FF0000");
            //api_app.setWhiteLabelingOptions (options);
            api_app.setDomain("wpengine.com");
            client.updateApiApp (api_app);

            SignatureRequest newRequest = (SignatureRequest)client.createEmbeddedRequest(embedReq);
```

**Comment by armyofda12mnkeys** [comment]
Note: here is the link the front-end code generates for the iframe for the one-off:

https://www.hellosign.com/editor/embeddedSign?signature_id=675cea0bac55258589fd862ae99ee615&token=ba74f33b9b0a49331240a583779150ed&ux_version=2&parent_url=http%3A%2F%2Flocalhost%3A9005%2Fscreener%2FQSCR-DDJD&skip_domain_verification=1&client_id=3069a2d180b801094df242fd22b84fcb&user_culture=en_US&white_labeling_options=%7B%22link_color%22:%22FF0000%22,%22primary_button_color%22:%22

and the options i used:
"uxVersion": 2,
              "skipDomainVerification": true,
              "allowCancel": true,
              'whiteLabelingOptions': {
                'link_color': '#FF0000',
                'primary_button_color' : '#00FF00'
              },
not sure if i see primary_button_color #00FF00 passed in that url.

**Comment by cmpaul** [comment]
@armyofda12mnkeys I'm going to remove your last comment just to prevent any sensitive data being posted here. Because of your comment, I spotted a bug in our embedded.js code, which I've resolved. Turns out we don't handle submitting more than one whiteLabelingOption at a time. It will need review from my team so it will likely be fixed early next week but you can track it here: https://github.com/HelloFax/hellosign-embedded/pull/16.

In the meantime, in order to update an existing app, use the `HelloSignClient.getApiApp(String clientId)` function to first retrieve the `ApiApp`, then update the white labeling settings on it, and finally submit the updated app via `HelloSignClient.updateApiApp(ApiApp app)`.

**Comment by armyofda12mnkeys** [comment]
Hey @cmpaul , 
i'll relook at the client-side whiteLabelingOptions in a few weeks when that fix is in...
For the server-side options, Im getting the error:
"com.hellosign.sdk.HelloSignException: An app with the same name already exists"
Im just getting the 'current app' and updating it i think as you suggested but not sure why its erroring:
Any ideas?

```
            EmbeddedRequest embedReq = new EmbeddedRequest(client_id, request);
            HelloSignClient client = new HelloSignClient(api_key);

            ApiApp api_app = client.getApiApp(client_id);
            api_app.setLinkColor ("#FF0000");
            api_app.setPrimaryButtonColor ("#00FF00");
            client.updateApiApp (api_app);

            SignatureRequest newRequest = (SignatureRequest)
```client.createEmbeddedRequest(embedReq);

**Comment by cmpaul** [comment]
@armyofda12mnkeys That definitely sounds suspicious. Let me test it out on my end and get back to you.

**Comment by cmpaul** [comment]
@armyofda12mnkeys Thanks to your feedback, I spotted a bug in our PUT request for updating an ApiApp. Just patched this as part of the 3.5.2 release. Give that a shot and let me know how that works!

**Comment by armyofda12mnkeys** [comment]
Hey @cmpaul , I tested and it looks good (just had to fix the invalid_contrast_ratio errors as I was initially testing with some goofy random/bright colors :) ). Thanks again!

**Comment by cmpaul** [comment]
@armyofda12mnkeys Awesome 😺
