### ISSUE TITLE
NPE when creating HelloSignClient

### ISSUE THREAD

**Issue by zlangbert** [HelloFax/hellosign-java-sdk#2]
The constructor of `HelloSignClient` looks for system properties to override certain configuration but System.getProperty returns null if the property doesn't exist, causing an NPE when it checks if the property is empty.

**Comment by cmpaul** [comment]
Zach,

Apologies for that! I've just patched this and moved the SDK to version 3.2.1. Please update and let me know if you see any issues going forward.

Related commit: https://github.com/HelloFax/hellosign-java-sdk/commit/d3769b9e53224bc22975dc58e961703344b710e1

Chris
