### ISSUE TITLE
Signer Order in embedded template POST ignored

### ISSUE THREAD

**Issue by radhack** [HelloFax/hellosign-java-sdk#25]
The Signer Order int included in the embedded template draft POST is not honored. There doesn't appear to be an error returned, and the template draft gets created and the claim url is returned in the POST response object as normal, but the Signer Order isn't assigned:

draft.addSignerRole("Tenant1", 1);
draft.addSignerRole("Signer2", 2);

The SignerRoles as passed, but the Signer Order int appears to be ignored.

**Comment by cmpaul** [comment]
@radhack This is because you also need to set:

```java
draft.setOrderMatters(true);
```

Try that and let me know if that works.

**Comment by radhack** [comment]
Thanks @cmpaul - that works like a charm!
