### ISSUE TITLE
correct way to set an Editable (and prefilled) Field?

### ISSUE THREAD

**Issue by armyofda12mnkeys** [HelloFax/hellosign-java-sdk#26]
So in my online template via the Hellosign template drag + drop GUI i setup a field called '___patient_fullname___'.
I set its 'Me (when sending)' to signify the API will prefilll it.
I noticed you can't set in the GUI if its editable also (and if so, if its required).

So i have to when i send up the data set if its editable. 
The usual code i have for other prefilled fields looks like:
`request.setCustomFieldValue ("___patient_fullname___", "John TestingFullname");`
but there is no optional params to do something like so (is this correct?):
`request.setCustomFieldValue ("___patient_fullname___", "John TestingFullname", "AllowedEditorRole", isRequiredBoolean);`

so i had to create a helper class:
```
public class HellosignCustomFieldHelper
{
    public static void setCustomField (TemplateSignatureRequest request, String key, String value, String editor, boolean isRequired ) {
        CustomField x = new CustomField();
        x.setEditor (editor); //this seems needed to make the field required by the 1 role we assigned to the Template in the GUI settings
        x.setIsRequired (isRequired);
        x.setName (key);
        x.setValue (value);
        //x.setType (FieldType.text);
        request.addCustomField (x);
    }
    public static void setCustomField (TemplateSignatureRequest request, String key, String value) {
        request.setCustomFieldValue (key, value);
    }
}
...
//regular non-editable field
HellosignCustomFieldHelper.setCustomField (request, "___patient_address___", "101 Cool lane");
//convert to editable field; overloaded method
HellosignCustomFieldHelper.setCustomField (request, "___patient_fullname___", "John TestingFullname", "AllowedEditorRole", true);

```

Does this all look like the correct way to set a prefilled field thats editable by the user (a mix of GUI and non-GUI api setting set via CustomField class)?

**Comment by cmpaul** [comment]
@armyofda12mnkeys Yes, this looks correct (I agree that the API for `CustomField` is verbose). I'll look into adding a convenience method for `setCustomFieldValue()` with my next update.

**Comment by cmpaul** [comment]
@armyofda12mnkeys It looks like we actually have that convenience method I mentioned above. Try using `TemplateSignatureRequest.setCustomFieldValue(fieldName, value)`.
