### ISSUE TITLE
Allow unused custom fields

### ISSUE THREAD

**Issue by armyofda12mnkeys** [HelloFax/hellosign-java-sdk#29]
I have 2 templates now which I dynamically switch to in the app (and there will be more templates in the future).
One template is for Patients, and the other is for Patient+Caregivers.
so i will always send 10 fields for patients (Firstname, Lastname, etc), 
and optionally send an additional 10 fields dynamically if Im also sending Caregiver information (which are collected in 1 form/page in our app). 
I will always add 5 more fields for the their Doctor's information (information from another form/page in our app), 
and always send over a few special questions pulled elsewhere from our questionnaire (gender, DOB, if they smoke, etc)

Now I dynamically pick one of the 2 templates, then just send all appropriate vars and the template should just use what it needs. But i think the API requires you to use _everything_ you send up otherwise it errors. You cant send extra fields you may use but aren't using currently.

It would be nice if we can allow the developer to send up all their custom vars, and the server will just prefill what the template uses. Otherwise, I have to dynamically figure out which fields I'm sending up for specific templates, and that may not be nice if our Marketing department decides one day they want to display DOB and Gender fields (in TemplatePatient and TemplateCaregiver) and then decide a week later to remove from TemplatePatient (but keep in TemplateCaregiver). It would cause an error to happen for TemplatePatient if Im still sending up the variable.
If the API were to opt-into lax validation of variables, then Marketing could make changes without IT updating the code on which variables to send up. Something like so:

```
client.checkAllCustomFieldKeyExistance(false); //by default, set to true
request.setCustomFieldValue ('gender', 'Male'); //used
request.setCustomFieldValue ('DOB', '12/17/1982'); //not used, but maybe template updated tomorrow and if so this will be used... at least won't error because checkAllCustomFieldKeyExistance is set
etc
```

Otherwise I have to check which template im using, and dynamically figure out which fields i want to send upTemplatePatient  (which is fine for example for the Caregiver fields which arent applicable to the Patient template, but some fields theoretically could be used at any point in both templates like Gender/DOB/etc).

**Comment by armyofda12mnkeys** [comment]
Maybe I can make it simpler:

Having ___patient_dob___ in the doc/template
but not sending up that variable is fine ...

Not having ___patient_dob___ in the doc/template,
and sending up ___patient_dob___ is not fine.

Since Marketing is setting up the templates, it would be nice if as a developer I can just send up all vars and let the template figure out what to use/prefill and not use (it can just avoid vars that aren't in the template).

**Comment by cmpaul** [comment]
@armyofda12mnkeys Are you able to [fetch the Template object](http://static.javadoc.io/com.hellosign/hellosign-java-sdk/3.5.6/com/hellosign/sdk/HelloSignClient.html#getTemplate-java.lang.String-) first, and then use that to dynamically request the fields you need from the user (and also dynamically submit those fields when you send the request)?

**Comment by cmpaul** [comment]
@armyofda12mnkeys I'll consider this issue closed shortly unless I hear back from you. Thanks!
