### ISSUE TITLE
Implement reported_for_app_id

### ISSUE THREAD

**Issue by angelafield** [HelloFax/hellosign-java-sdk#3]
A user reports: Also, I can't use your api to check for null [for reported_for_app_id] to ignore this as I don't see that you have implemented the reported_for_app_id field in your java api (but you have implemented, reported_for_account_id). This could be easily added with a simple copy/paste... For now; I am doing my own check; but it would be nice to see in the API.

@cmpaul

**Comment by cmpaul** [comment]
@angelafield This is fixed as of version 3.3.3.
