### ISSUE TITLE
get access to signature_request_id and signature_id fields returned from API in both embedded and non-embedded flow

### ISSUE THREAD

**Issue by armyofda12mnkeys** [HelloFax/hellosign-java-sdk#37]
In the non-embedded flow (send an email to user), I can't access these api vars with the java sdk, but I do see them come across the API in Fiddler.

signature_request->signature_request_id
signature_request->signatures->signature_id
We'd like to store these in our DB. Possible to add in the SDK?

For embedded flow, i can at least access the signature_id with:
           ```
            TemplateSignatureRequest request = new TemplateSignatureRequest();
            request.setTemplateId(template_id);
            EmbeddedRequest embedReq = new EmbeddedRequest(client_id, request);
            SignatureRequest newRequest = (SignatureRequest) client.createEmbeddedRequest(embedReq);                            
            List<Signature> signatures = newRequest.getSignatures ();
            Signature patient_signature = signatures.get (0);
            String signature_id = patient_signature.getId ();
            EmbeddedResponse response = client.getEmbeddedSignUrl(signature_id);
            esign_url = response.getSignUrl();
            //hmm not sure i can get the signature_request_id? maybe that should be under request.getId(), but doesn't return anything?

```

We would like to store this in our DB so possibly in future we can get status with:
GET /signature_request/[:signature_request_id]
We currently use the signature_id in embedded flow to recreate the esign in an email link if the user didn't sign in our original embedded flow.
Just thought would be nice to consistently get both **signature_request_id** and **signature_id** 
on embedded or non-embedded flow.

**Comment by cmpaul** [comment]
Hi @armyofda12mnkeys !

The values you refer to can already be retrieved using the existing model API as follows:

* "signature_request->signature_request_id" can be accessed using `SignatureRequest.getId()`
* "signature_request->signatures->signature_id" can be accessed a few different ways. You can either iterate over the signatures and retrieve the ID for each using `Signature.getId()` or retrieve a specific signature using `SignatureRequest.getSignature(email, name);` and then grab the ID the same way.

Let me know if this answers your question. If I don't hear back from you, I'll consider this issue closed.

Thanks!
