### ISSUE TITLE
Add retry logic to HTTP requests

### ISSUE THREAD

**Issue by cmpaul** [HelloFax/hellosign-java-sdk#38]
When an HTTP request fails, retry with (configurable) exponential back-off and jitter.

This prevents clients from needing to implement retry logic themselves.

**Comment by mveitas** [comment]
https://github.com/jhalterman/failsafe is a great lightweight library to do this

**Comment by jspaetzel** [comment]
I'm closing this because the application implementing the sdk should implement retry logic depending on the result.
