### ISSUE TITLE
HelloSignClient#getFiles() doesn't give the option to retrieve the file URL

### ISSUE THREAD

**Issue by rscarvalho** [HelloFax/hellosign-java-sdk#43]
According to the [API Docs](https://app.hellosign.com/api/reference#get_files) the `get_url` query param could be specified in order to get a String with a URL to download the document instead of the file bytes.

There is however no override nor other methods in the Java API that we could specify to retrieve the URL instead of the file bytes.

**Comment by cmpaul** [comment]
Deployed as version 4.0.2.
