### ISSUE TITLE
Handle 409 responses

### ISSUE THREAD

**Issue by cmpaul** [HelloFax/hellosign-java-sdk#46]
Per @mveitas:

Handle the case of a 409 response when retrieving signature request files.

> I saw that the library is still at 1.7, if this was 1.8, Optional would be a great to use for things like 404s instead of throwing an exception.

**Comment by jspaetzel** [comment]
This can be grouped in with https://github.com/HelloFax/hellosign-java-sdk/issues/45 for customized handling of expected response types.
