### ISSUE TITLE
remove isOnline() function from JavaSDK as it is no longer supported

### ISSUE THREAD

**Issue by alexmac05** [HelloFax/hellosign-java-sdk#54]
remove isOnline() function from JavaSDK as it is no longer supported

isOnline = (httpClient.options(BASE_URI).asHttpCode() == HttpURLConnection.HTTP_OK);

http://static.javadoc.io/com.hellosign/hellosign-java-sdk/3.5.6/com/hellosign/sdk/HelloSignClient.html#isOnline--

This function call is no longer supported in the hellosign API so it should be removed from the JavaSDK.

**Comment by cmpaul** [comment]
Deprecated as of v4.0.4
