### ISSUE TITLE
Api on Java 6

### ISSUE THREAD

**Issue by wilsoncmartins** [HelloFax/hellosign-java-sdk#58]
Hi,

I have a project that can not be upgrade to java 7 or 8. This project runs on java 6.

Is there a version of api that runs on java 6?

I did the checkout of the api in my workspace java 6, the method that does not work is this one:

![image](https://cloud.githubusercontent.com/assets/15194075/25807514/78f2845c-33dd-11e7-8d53-efccac3d2f24.png)

on class AbstractHttpRequest.java.

For while, to work around it i had maked some changes on:
https://github.com/wilsoncmartins/hellosign-java-sdk-master-jdk-6

Thanks.

**Comment by cmpaul** [comment]
Hi @wilsoncmartins,

You can also try version 3.5.6, which is the last tagged version targeted for Java 6:
https://github.com/HelloFax/hellosign-java-sdk/tree/3.5.6

Chris

**Comment by wilsoncmartins** [comment]
I searched old versions and sow the project started in java 7.

**Comment by cmpaul** [comment]
@wilsoncmartins You're right, sorry for the confusion. Sounds like you've got a fork that is compiling for Java 6, though, so you're good to go?

**Comment by wilsoncmartins** [comment]
@cmpaul  Yes, you are.
Thanks for listening and answer.
