### ISSUE TITLE
Signer groups

### ISSUE THREAD

**Issue by wilsoncmartins** [HelloFax/hellosign-java-sdk#59]
Good Morning,

Someone know if there is a plan to implement something like "signer groups" for exemplo in cases where there are a group of people and out of that group 1 needs to sign. Futhermore, it could be a husband and a wife. One needs to sign, but once one does, then the signature can be complete.

Thansk.

**Comment by cmpaul** [comment]
HelloSign doesn't currently support a signer group feature, but it is being considered for our product roadmap!
