### ISSUE TITLE
Got File_error after I upgraded to latest sdk version 3.3.4

### ISSUE THREAD

**Issue by empireyc** [HelloFax/hellosign-java-sdk#6]
The scenario is that there are two signers need to sign the document, one is using embedded signing, the other one is using email to sign. Since embedded signing doesn't have email sent to the signer, so I'm implementing this by after the first signer signed the document, I create a signature request using the document that the first signer signed and send it to the second signer, so the second signer will receive an email to sign and the document contains the first signer's signature. I saw that in the dashboard, the signature request that I created for the second signer can be sent, but the call back contained error.
It used to work in this way before I upgraded the sdk on Dec 4th. I used to use sdk-3.2.2, now I upgraded to sdk-3.3.4 which should be the latest version. I don't know if this is related to cause this error. Please take a look, thanks!

**Comment by cmpaul** [comment]
Hi @empireyc !

Your scenario should work. Are you receiving this error when you download the document for the first signature request?

**Comment by empireyc** [comment]
Hi @cmpaul 
I am receiving this for the second request. The error is Unable to retrieve files from S3: Array ( [0] => /opt/hellofax/web/uploads/documents/2015/12/15/d720406b8875fceb82b0a4516491646a34c13ee3/intermediate.pdf )

**Comment by cmpaul** [comment]
@empireyc That sounds like a potential error on the HelloSign side. Can you provide me with some sample calls to reproduce this error? I'll investigate on my end as well.

**Comment by cmpaul** [comment]
@empireyc I'm closing this issue. If you continue to see problems, please contact us at apisupport@hellosign.com. Thanks!
