### ISSUE TITLE
By Pass Signer

### ISSUE THREAD

**Issue by wilsoncmartins** [HelloFax/hellosign-java-sdk#60]
is it possible to have in the document the tags [sig | req | signer0] and [sig | req | signer1], but during sending via api the system not have signer1 and for that reason "say" to api: ignore or by pass in signer1?

**Comment by jyoung488** [comment]
Thanks for the suggestion @wilsoncmartins! This will need to be logged as a feature request for the API. Please feel free to write into apisupport@hellosign.com if you have additional questions.
