### ISSUE TITLE
Missing Signature Statuses

### ISSUE THREAD

**Issue by codylerum** [HelloFax/hellosign-java-sdk#61]
Example from JSON

"status_code": "error_text_tag",

**Comment by codylerum** [comment]
Looks like quite a few are missing.

https://app.hellosign.com/api/reference#StatusCodes

**Comment by cmpaul** [comment]
@codylerum Thanks! Will get these added.

**Comment by codylerum** [comment]
@cmpaul There is a PR for it already as well. I hate how you can't create a PR from an existing issue.
