### ISSUE TITLE
HelloSignException no longer returns HTTP status code

### ISSUE THREAD

**Issue by yadavharsh** [HelloFax/hellosign-java-sdk#66]
Starting with SDK version 4.0.6, the HelloSignException no longer returns an http error code along with the message.
For e.g.
com.hellosign.sdk.HelloSignException: This request has already been signed
type = conflict
httpCode = null

This contradicts the API documentation:
https://app.hellosign.com/api/reference#ErrorNames

**Comment by yadavharsh** [comment]
Hi, Any update on this? We cannot upgrade to the latest SDK due to this breaking change.

**Comment by radhack** [comment]
Hi @yadavharsh - this is on our radar, and we'll take a look and have an update in the next week or so.

Thanks!

**Comment by cmpaul** [comment]
Hi @yadavharsh - Sorry for the delay on this. Can you provide a bit more detail about the request you're making? Looks like you're constructing a signature request and then attempting to generate a sign URL for embedded signing (and it's already been signed). Is that right?

**Comment by yadavharsh** [comment]
HelloSignException used to return getHttpCode() == 409 (for conflicts)
Also, as per the below documentation we should see the error code too:
https://app.hellosign.com/api/reference#WarningsAndErrors

However, the error code is no longer returned (its null)

**Comment by cmpaul** [comment]
Thanks @yadavharsh ! We're able to reproduce and should have a patch out shortly. Again, thanks for your patience!

**Comment by radhack** [comment]
Thanks @yadavharsh - we just published v4.0.9 to address this (thanks for bringing it to our attention!). Could you test and let us know?

**Comment by radhack** [comment]
Closing this - haven't heard it's not working and it's been tested thoroughly.
