### ISSUE TITLE
Missing ability to add redirect URL

### ISSUE THREAD

**Issue by jyoung488** [HelloFax/hellosign-java-sdk#70]
AbstractResource should have a public function to add a redirect URL to the signature request with file and with template

**Comment by radhack** [comment]
`request.setRedirectUrl();` works with `client.sendSignatureRequest();` (so when creating a signature request based on a file or fileUrl).

`request.setRedirectUrl();` is available to TemplateSignatureRequest, but isn't passed to HelloSign with `client.sendTemplateSignatureRequest();` for some reason.

**Comment by borlandohb** [comment]
@radhack that is exactly what i experienced when debugging, for some reason getRedirectUrl() doesn't get called when setting the post fields

**Comment by radhack** [comment]
Addressed with release version 4.0.8
