### ISSUE TITLE
Use exception constructor that takes httpCode in asHttpCode method

### ISSUE THREAD

**Issue by gwongz** [HelloFax/hellosign-java-sdk#78]
When calling methods that return the HTTP response code (i.e. `cancelSignatureRequest`), I also want to access the status code when an exception is thrown. Right now the status code can only be accessed by parsing the exception message.

**Comment by gwongz** [comment]
Submitted PR that is ready for review: https://github.com/HelloFax/hellosign-java-sdk/pull/79

**Comment by jspaetzel** [comment]
Closing this since changes for this have been merged.
