### ISSUE TITLE
Can i have radio button or similar to radio button using Java Code

### ISSUE THREAD

**Issue by Dilip12344** [HelloFax/hellosign-java-sdk#80]
[Reference](https://app.hellosign.com/api/reference#Constants)

Document doc = new Document();
doc.setFile(new File("C:\\Users\\kuldeepc\\Desktop\\doc1.pdf"));
FormField cb1 = new FormField();
		cb1.setType(FieldType.checkbox);
		cb1.setName("CB"); 
		cb1.setSigner(0); // Signer indexes are zero-based
		cb1.setHeight(25);
		cb1.setWidth(25);
		cb1.setPage(1); // 1-based indexing, relative to the document
		cb1.setX(100);
		cb1.setY(200);
		doc.addFormField(cb1);
Is there anything which work same as radio button, i have multiple checkbox but i wants to select only one at a time. Please suggest me

**Comment by jyoung488** [comment]
Hi @Dilip12344 - This would be considered grouped checkboxes. For more assistance, please email apisupport@hellosign.com and we'll be able to provide you with more context. Thank you!
