### ISSUE TITLE
Allow page size to be passed to the getTemplates() method.

### ISSUE THREAD

**Issue by Framinus** [HelloFax/hellosign-java-sdk#85]
Currently, the page number parameter can be passed to getTemplates(), but the page_size parameter cannot be set. 

The method to be updated is HelloSignClient.java#L510:

![image](https://user-images.githubusercontent.com/24632499/49673825-a3486f00-fa24-11e8-8ee2-9d3c1ef9b250.png)

**Comment by jspaetzel** [comment]
Hey @Framinus thanks for opening this issue! I've opened a PR to address this. https://github.com/HelloFax/hellosign-java-sdk/pull/87

**Comment by jspaetzel** [comment]
This is available as of 4.0.11.
